const roleOptions = [
    { value: "", label: "Select" },
    { value: "academician", label: "Academician" },
    { value: "ai researcher", label: "AI Researcher" },
    { value: "bioinformatician", label: "Bioinformatician" },
    { value: "biomedical engineer", label: "Biomedical Engineer" },
    { value: "biostatistician", label: "Biostatistician" },
    { value: "clinical informatics specialist", label: "Clinical Informatics Specialist" },
    { value: "data scientist", label: "Data Scientist" },
    { value: "dentist", label: "Dentist" },
    { value: "general practitioner", label: "General Practitioner" },
    { value: "genetic counselor", label: "Genetic Counselor" },
    { value: "health it specialist", label: "Health IT Specialist" },
    { value: "healthcare administrator", label: "Healthcare Administrator" },
    { value: "healthcare consultant", label: "Healthcare Consultant" },
    { value: "machine learning engineer", label: "Machine Learning Engineer" },
    { value: "marketing specialist", label: "Marketing Specialist" },
    { value: "medical student", label: "Medical Student" },
    { value: "medical technologist", label: "Medical Technologist" },
    { value: "nurse", label: "Nurse" },
    { value: "nurse practitioner", label: "Nurse Practitioner" },
    { value: "pharmacist", label: "Pharmacist" },
    { value: "physician assistant", label: "Physician Assistant" },
    { value: "product manager", label: "Product Manager" },
    { value: "project manager", label: "Project Manager" },
    { value: "psychiatrist", label: "Psychiatrist" },
    { value: "psychologist", label: "Psychologist" },
    { value: "public health official", label: "Public Health Official" },
    { value: "radiologist", label: "Radiologist" },
    { value: "researcher", label: "Researcher" },
    { value: "resident physician", label: "Resident Physician" },
    { value: "software engineer", label: "Software Engineer" },
    { value: "specialist physician", label: "Specialist Physician" },
    { value: "surgeon", label: "Surgeon" },
    { value: "teacher", label: "Teacher" },
    { value: "telemedicine specialist", label: "Telemedicine Specialist" },
    { value: "therapist", label: "Therapist" },
    { value: "undergraduate student", label: "Undergraduate Student" },
    { value: "graduate student", label: "Graduate Student" },
];

export default roleOptions;
